Require conflicting dependencies
Tests were failing and we could see messages like:

warning: toplevel constant Answer referenced by Poll::Answer
warning: toplevel constant Answer referenced by Poll::Question::Answer

Resulting in errors like:

NoMethodError:
  undefined method `by_question' for #<Class:0x00007fdab16c50a0>

ActionView::Template::Error:
	PG::UndefinedColumn: ERROR:	 column answers.question does not exist
	LINE 1: ...TINCT "answers"."author_id") FROM "answers" WHERE "answers"....

Apparently the lookup was not correclty being performed, due to
conflicting names.

"Naming conflicts of this kind are rare in practice, but if one
occurs, require_dependency provides a solution by ensuring that
the constant needed to trigger the heuristic is defined in the
conflicting place."

https://guides.rubyonrails.org/v5.0/autoloading_and_reloading_constants.html